const admin = require('firebase-admin');
admin.initializeApp();

const { notifyGroupOnNewMatch } = require('./handlers/notifyOnNewMatch');
const { notifyUserOnInvite } = require('./handlers/notifyOnInvite');
const { calculateMvpWinners } = require('./handlers/calculateMvpWinners');
const { remindMvpVoters } = require('./handlers/remindMvpVoters');
const { editMatch } = require('./handlers/editMatch');
const { deleteMatch } = require('./handlers/deleteMatch');
const { notifyAdminsOnJoinRequest } = require('./handlers/notifyOnJoinRequest');
const { notifyUserOnJoinRequestUpdate } = require('./handlers/notifyOnJoinRequestUpdate');
const { sendMatchReminders, onMatchCreated, onMatchUpdated, onChallengeMatchCreated, onChallengeMatchUpdated, onMatchByTeamsCreated, onMatchByTeamsUpdated } = require('./handlers/matchRemindersHandler');
const { editChallengeMatch } = require('./handlers/editChallengeMatch');
const { deleteChallengeMatch } = require('./handlers/deleteChallengeMatch');
const { calculateChallengeMvpWinners } = require('./handlers/calculateChallengeMvpWinners');
const { remindChallengeMvpVoters } = require('./handlers/remindChallengeMvpVoters');

exports.notifyGroupOnNewMatch = notifyGroupOnNewMatch;
exports.notifyUserOnInvite = notifyUserOnInvite;
exports.calculateMvpWinners = calculateMvpWinners;
exports.remindMvpVoters = remindMvpVoters;
exports.editMatch = editMatch;
exports.deleteMatch = deleteMatch;
exports.notifyAdminsOnJoinRequest = notifyAdminsOnJoinRequest;
exports.notifyUserOnJoinRequestUpdate = notifyUserOnJoinRequestUpdate;
exports.sendMatchReminders = sendMatchReminders;
exports.onMatchCreated = onMatchCreated;
exports.onMatchUpdated = onMatchUpdated;
exports.onChallengeMatchCreated = onChallengeMatchCreated;
exports.onChallengeMatchUpdated = onChallengeMatchUpdated;
exports.onMatchByTeamsCreated = onMatchByTeamsCreated;
exports.onMatchByTeamsUpdated = onMatchByTeamsUpdated;
exports.editChallengeMatch = editChallengeMatch;
exports.deleteChallengeMatch = deleteChallengeMatch;
exports.calculateChallengeMvpWinners = calculateChallengeMvpWinners;
exports.remindChallengeMvpVoters = remindChallengeMvpVoters;
